language: android

android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-28
  - extra-google-m2repository
  - extra-android-m2repository
jdk:
  - oraclejdk8
branches:
  only:
  - master
jobs:
  include:
  - stage: check
    name: "lint"
    script: ./gradlew clean lint
  - stage: check
    name: "ktlint"
    script: ./gradlew clean ktlint
  - stage: check
    name: "test"
    script: ./gradlew clean test